test: New make flag "DEBUG" which enables output from zshrc parsing

diff --git a/test/_test6/script b/test/_test6/script
--- a/test/_test6/script
+++ b/test/_test6/script
@@ -3,6 +3,10 @@ if ! is-at-least 5.0.7; then
     command touch skip
     return 0
 fi
--zcrasis_action_reload >/dev/null || { echo "Failed to parse zshrc" | tee zshrc.test; return 0; }
+if (( DBG )); then
+    -zcrasis_action_reload || { echo "Failed to parse zshrc" | tee zshrc.test; return 0; }
+else
+    -zcrasis_action_reload >/dev/null || { echo "Failed to parse zshrc" | tee zshrc.test; return 0; }
+fi
 -zcrasis_action_move_down 2 1
 -zcrasis_action_save
